# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-28 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20191119_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_username',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Github username'),
        )
    ]
